
services:
  discord_bot:
    container_name: people_collection_bot
    logging:
      driver: "json-file"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: people_collection
      POSTGRES_PASSWORD: people_collection
    ports:
      - "5432:5432"
networks:
  db:
    driver: brdige

